postgres:
  host: "localhost"
  port: 5432
  user: "datasus_user"
  password: "senha_segura"
  database: "datasus"

upload_specific:
  target_table: "sih_servicos_profissionais"  # Nome da tabela no PostgreSQL onde os dados serão inseridos
  specific_file: ""  # Caminho do arquivo específico a ser processado, caso necessário
  states:
    - AC
    - AL
    - AP
    - AM
    - BA
    - CE
    - DF
    - ES
    - GO
    - MA
    - MT
    - MS
    - MG
    - PA
    - PB
    - PR
    - PE
    - PI
    - RJ
    - RN
    - RS
    - RO
    - RR
    - SC
    - SP
    - SE
    - TO

download:
  groups:
    SIA:
      PA: "Grupo PA - Produção Ambulatorial"
  states:  # Siglas dos estados: Minas Gerais, Paraná, São Paulo
    - MG
    - PR
    - SP
  years:  # Intervalo de anos para download
    - 2018
    - 2024

paths:
  parquet_files: "parquet_files/SIA/PA"  # Diretório onde os arquivos baixados serão armazenados
  logs: "logs"  # Diretório onde os logs do processo serão salvos
  progress_file: "progress_SIA_PA.txt"  # Arquivo que armazenará o progresso do download

parameters:
  max_retries: 3         # Número máximo de tentativas em caso de falha
  retry_delay: 5         # Tempo (em segundos) entre tentativas
  backoff_factor: 2      # Fator de incremento do tempo de espera entre tentativas
