# models/sih_sp.py

from sqlalchemy import Column, Integer, String, Float, Date, Boolean
from . import Base

class SIH_SP(Base):
    __tablename__ = 'sih_servicos_profissionais'

    id = Column(Integer, primary_key=True, autoincrement=True)
    SP_GESTOR = Column(String(255), nullable=True)
    SP_UF = Column(String(2), nullable=True)
    SP_AA = Column(Integer, nullable=True)
    SP_MM = Column(Integer, nullable=True)
    SP_CNES = Column(String(10), nullable=True)
    SP_NAIH = Column(String(50), nullable=True)
    SP_PROCREA = Column(String(50), nullable=True)
    SP_DTINTER = Column(Date, nullable=True)
    SP_DTSAIDA = Column(Date, nullable=True)
    SP_NUM_PR = Column(String(50), nullable=True)
    SP_TIPO = Column(String(50), nullable=True)
    SP_CPFCGC = Column(String(14), nullable=True)
    SP_ATOPROF = Column(String(50), nullable=True)
    SP_TP_ATO = Column(String(50), nullable=True)
    SP_QTD_ATO = Column(Integer, nullable=True)
    SP_PTSP = Column(String(50), nullable=True)
    SP_NF = Column(String(50), nullable=True)
    SP_VALATO = Column(Float, nullable=True)
    SP_M_HOSP = Column(Integer, nullable=True)
    SP_M_PAC = Column(Integer, nullable=True)
    SP_DES_HOS = Column(String(255), nullable=True)
    SP_DES_PAC = Column(String(255), nullable=True)
    SP_COMPLEX = Column(String(50), nullable=True)
    SP_FINANC = Column(String(50), nullable=True)
    SP_CO_FAEC = Column(String(50), nullable=True)
    SP_PF_CBO = Column(String(50), nullable=True)
    SP_PF_DOC = Column(String(50), nullable=True)
    SP_PJ_DOC = Column(String(50), nullable=True)
    IN_TP_VAL = Column(String(50), nullable=True)
    SEQUENCIA = Column(Integer, nullable=True)
    REMESSA = Column(String(50), nullable=True)
    SERV_CLA = Column(String(50), nullable=True)
    SP_CIDPRI = Column(String(50), nullable=True)
    SP_CIDSEC = Column(String(50), nullable=True)
    SP_QT_PROC = Column(Integer, nullable=True)
    SP_U_AIH = Column(String(50), nullable=True)
